# Generated by Django 4.1.4 on 2023-01-02 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0010_alter_itemorder_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_menu_item', to='LittleLemonAPI.menuitem'),
        ),
    ]
