# Generated by Django 4.1.4 on 2023-01-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0014_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemorder',
            unique_together={('order', 'menu_item')},
        ),
    ]
