# Generated by Django 4.1.4 on 2023-01-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0015_alter_itemorder_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
