# Generated by Django 4.1.4 on 2023-01-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0016_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, max_length=31, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=9),
        ),
    ]
