# Generated by Django 4.1.4 on 2023-01-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0017_category_slug_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=31),
        ),
    ]
