# Generated by Django 4.1.4 on 2023-01-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0019_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, max_length=31, unique=True),
            preserve_default=False,
        ),
    ]
