# Generated by Django 4.1.4 on 2023-01-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0022_alter_category_title_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=9),
            preserve_default=False,
        ),
    ]
